---
# handlers file for ansible-zimbra

- name: restart named
  ansible.builtin.service:
    name: named
    state: restarted

- name: restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
